baseURL: 'http://materialstyle.github.io/materialstyle'
languageCode: 'en'
title: 'Material Style'

markup:
  goldmark:
    renderer:
      unsafe:           true
  highlight:
    noClasses:          false
  tableOfContents:
    startLevel:         2
    endLevel:           6

buildDrafts:            true
buildFuture:            true

enableRobotsTXT:        true
metaDataFormat:         "yaml"
disableKinds:           ["404", "taxonomy", "term", "RSS", "section"]

publishDir: "_site"

module:
  mounts:
  - source: dist
    target: static/3.0/dist
  - source: site/content
    target: content
  - source: site/static
    target: static
  - source: site/layouts
    target: layouts
  - source: site/data
    target: data
  - source: site/assets
    target: assets

related:
  includeNewer: false
  indices:
    - name: keywords
      weight: 100
    - name: date
      weight: 10
  threshold: 80
  toLower: false

params:
  description:          "A Material Design UI Library based on Bootstrap"
  authors:              "Neeraj Kumar Das"

  current_version:      "3.0.0"
  docs_version:         "3.0"
