baseURL: 'http://materialstyle.github.io/materialstyle'
languageCode: 'en-us'
title: 'My New Hugo Site'


markup:
    goldmark:
        renderer:
            unsafe:           true
    highlight:
        noClasses:          false
    tableOfContents:
        startLevel:         2
        endLevel:           6

buildDrafts:            true
buildFuture:            true

enableRobotsTXT:        true
metaDataFormat:         "yaml"
disableKinds:           ["404", "taxonomy", "term", "RSS"]

publishDir:             "_site"

module:
    mounts:
    - source: site/content
      target: content
    - source: site/static
      target: static
    - source: site/layouts
      target: layouts
    - source: site/data
      target: data
    - source: site/assets
      target: assets
    - source: site/i18n
      target: i18n
    - source: site/archetypes
      target: archetypes

- name: Hugo setup
  uses: peaceiris/actions-hugo@v2.4.13
  
- name: GitHub Pages action
  uses: peaceiris/actions-gh-pages@v3.7.3

